# Generated by Django 2.2.11 on 2020-05-10 08:43

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, verbose_name='company name')),
                ('city', models.CharField(max_length=60)),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='purchases.ProductCategory')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shared.Unit')),
            ],
            options={
                'ordering': ('name',),
                'default_related_name': 'products',
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity in the selected product unit.', max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Price is in USD.', max_digits=10)),
                ('year', models.PositiveIntegerField(choices=[(2008, '2008/2009'), (2009, '2009/2010'), (2010, '2010/2011'), (2011, '2011/2012'), (2012, '2012/2013')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='purchases.Product')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='purchases.Supplier')),
            ],
            options={
                'verbose_name': 'Purchasing Batch',
                'verbose_name_plural': 'Purchasing Batches',
                'ordering': ('-created_at',),
                'default_related_name': 'batches',
            },
        ),
    ]
