# Generated by Django 2.2.11 on 2020-05-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_auto_20200506_1849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'default_related_name': 'batches', 'ordering': ('-year',), 'verbose_name': 'Purchasing Batch', 'verbose_name_plural': 'Purchasing Batches'},
        ),
        migrations.AlterField(
            model_name='batch',
            name='year',
            field=models.PositiveIntegerField(choices=[('2008/2009', 2008), ('2009/2010', 2009), ('2010/2011', 2010), ('2011/2012', 2011), ('2012/2013', 2012)]),
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='batch',
            name='batch_round',
        ),
    ]
