# Generated by Django 2.2.11 on 2020-05-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_auto_20200506_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='year',
            field=models.PositiveIntegerField(choices=[(2008, '2008/2009'), (2009, '2009/2010'), (2010, '2010/2011'), (2011, '2011/2012'), (2012, '2012/2013')]),
        ),
    ]
