# Generated by Django 2.2.11 on 2020-05-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_supplier_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='quantity',
            field=models.DecimalField(decimal_places=3, help_text='Quantity in the selected product unit.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='batch',
            name='rate',
            field=models.DecimalField(decimal_places=3, help_text='Price is in USD.', max_digits=10),
        ),
    ]
