# Generated by Django 2.2.11 on 2020-05-07 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_auto_20200506_2037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'default_related_name': 'batches', 'ordering': ('-created_at',), 'verbose_name': 'Purchasing Batch', 'verbose_name_plural': 'Purchasing Batches'},
        ),
    ]
