# Generated by Django 2.2.11 on 2020-05-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_auto_20200507_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
