# Generated by Django 2.2.11 on 2020-05-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_batch_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='deleted'),
        ),
    ]
