# Generated by Django 2.2.11 on 2020-05-31 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_auto_20200526_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='lc_number',
            field=models.CharField(blank=True, default='', help_text='Document number for the letter of credit.', max_length=30, verbose_name='L/C number'),
        ),
    ]
