# Generated by Django 2.2.11 on 2020-05-31 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0007_batch_lc_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='lc_number',
            field=models.CharField(help_text='Document number for the letter of credit.', max_length=30, verbose_name='L/C number'),
        ),
    ]
