# Generated by Django 2.2.11 on 2020-06-06 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0009_batch_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'default_related_name': 'batches', 'ordering': ('-created_at',), 'permissions': [('close_batch', 'Close purchasing batch'), ('reopen_batch', 'Re-open purchasing batch')], 'verbose_name': 'Purchasing Batch', 'verbose_name_plural': 'Purchasing Batches'},
        ),
    ]
