# Generated by Django 2.2.11 on 2020-06-07 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0010_auto_20200606_1609'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Batch',
        ),
    ]
