# Generated by Django 2.2.11 on 2020-06-13 21:16

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0011_delete_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='fax_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True),
        ),
    ]
