# Generated by Django 2.2.11 on 2020-04-28 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('code', models.CharField(max_length=10)),
                ('type', models.CharField(choices=[('WEIGHT', 'Weight/Mass'), ('VOLUME', 'Volume'), ('LENGTH', 'Length/Distance'), ('COUNTER', 'Counter')], max_length=10)),
            ],
            options={
                'verbose_name': 'Measurement Unit',
                'verbose_name_plural': 'Measurement Units',
                'ordering': ('name',),
            },
        ),
    ]
