# Generated by Django 2.2.11 on 2020-04-07 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
