# Generated by Django 2.2.11 on 2020-03-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='company_name',
        ),
        migrations.AddField(
            model_name='supplier',
            name='name',
            field=models.CharField(default='', max_length=60, verbose_name='company name'),
            preserve_default=False,
        ),
    ]
