# Generated by Django 2.2.11 on 2020-04-07 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_customer_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='code',
            field=models.CharField(default='', max_length=4, unique=True),
            preserve_default=False,
        ),
    ]
