# Generated by Django 2.2.11 on 2020-04-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200417_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('STAFF', 'Staff'), ('MANAGEMENT', 'Management'), ('SUPPLIER', 'Supplier')], default='STAFF', max_length=30),
        ),
    ]
