# Generated by Django 2.2.11 on 2020-04-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('DISABLED', 'Disabled')], default='PENDING', max_length=30),
        ),
    ]
