# Generated by Django 2.2.11 on 2020-04-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STAFF', 'Staff'), ('MANAGEMENT', 'Management'), ('SUPPLIER', 'Supplier')], default='STAFF', max_length=30),
        ),
    ]
