# Generated by Django 2.2.11 on 2020-04-22 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200422_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('PENDING', 1), ('ACTIVE', 2), ('DISABLED', 3)], default='PENDING', max_length=30),
        ),
    ]
