# Generated by Django 2.2.11 on 2020-04-22 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200423_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[(1, 'Pending'), (2, 'Active'), (3, 'Disabled')], default=1, max_length=30),
        ),
    ]
