# Generated by Django 2.2.11 on 2020-04-22 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200423_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Active'), (3, 'Disabled')], default=1),
        ),
    ]
