# Generated by Django 2.2.11 on 2020-04-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='union',
            name='location',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
