# Generated by Django 2.2.11 on 2020-05-11 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='union',
            name='location',
        ),
    ]
