# Generated by Django 2.2.11 on 2020-05-12 09:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_union_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='union',
            options={'ordering': ('-updated_at',)},
        ),
        migrations.AddField(
            model_name='union',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='union',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterOrderWithRespectTo(
            name='union',
            order_with_respect_to=None,
        ),
    ]
