# Generated by Django 2.2.11 on 2020-05-26 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20200512_1247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='union',
            options={'ordering': ('name',)},
        ),
        migrations.AlterOrderWithRespectTo(
            name='location',
            order_with_respect_to=None,
        ),
    ]
