# Generated by Django 3.0 on 2020-03-21 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LC',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_number', models.CharField(max_length=12)),
            ],
            options={
                'verbose_name': 'Letter of Credit',
                'verbose_name_plural': 'Letter of Credits',
            },
        ),
        migrations.CreateModel(
            name='DistributionOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vessel', models.CharField(help_text='The name of the transportation vessel.', max_length=120)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distribution_orders', to=settings.AUTH_USER_MODEL)),
                ('lc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distribution_orders', to='allocations.LC', verbose_name='letter of credit')),
            ],
            options={
                'verbose_name': 'Distribution Order',
                'verbose_name_plural': 'Distribution Orders',
                'ordering': ('-created_at',),
                'default_related_name': 'distribution_orders',
            },
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity in meteric ton.', max_digits=12)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations', to=settings.AUTH_USER_MODEL)),
                ('distribution_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='allocations.DistributionOrder')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='shared.Location')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='shared.Region')),
                ('union', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='shared.Union')),
            ],
            options={
                'default_related_name': 'allocations',
                'order_with_respect_to': 'distribution_order',
            },
        ),
    ]
