# Generated by Django 2.2.11 on 2020-03-23 18:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_number', models.CharField(max_length=30, unique=True)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Price is in USD.', max_digits=10)),
                ('vessel', models.CharField(help_text='Shipment vessel name.', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_orders', to='shared.Product')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_orders', to='shared.Supplier')),
            ],
            options={
                'verbose_name': 'Delivery Order',
                'verbose_name_plural': 'Delivery Orders',
                'ordering': ('-created_at',),
                'default_related_name': 'delivery_orders',
            },
        ),
        migrations.CreateModel(
            name='InspectionReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='In meteric ton (MT)', max_digits=10)),
                ('delivery_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_report', to='orders.DeliveryOrder')),
            ],
        ),
        migrations.CreateModel(
            name='OrderAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='In meteric ton (MT)', max_digits=10)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_allcations', to='shared.Customer')),
                ('delivery_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_allcations', to='orders.DeliveryOrder')),
            ],
            options={
                'verbose_name': 'Delivery Order Allocation',
                'verbose_name_plural': 'Delivery Order Allocations',
                'ordering': ('buyer__name',),
                'default_related_name': 'order_allcations',
                'unique_together': {('delivery_order', 'buyer')},
            },
        ),
    ]
