# Generated by Django 2.2.11 on 2020-04-04 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import orders.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lc_number', models.CharField(max_length=30, unique=True, verbose_name='letter of credit number')),
                ('vessel', models.CharField(help_text='Shipment vessel name.', max_length=120)),
                ('bill_of_loading', models.CharField(help_text='Bill of loading (B/L) number.', max_length=30)),
                ('arrival_date', models.DateField(verbose_name='vessel arrival date')),
                ('status', models.CharField(choices=[('OPEN', 'open'), ('CLOSED', 'closed')], default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_orders', to='shared.Batch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Delivery Order',
                'verbose_name_plural': 'Delivery Orders',
                'ordering': ('-created_at',),
                'default_related_name': 'delivery_orders',
            },
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('country', django_countries.fields.CountryField(countries=orders.models.NeighbourCountry, max_length=2)),
                ('is_default', models.BooleanField(default=False, verbose_name='default')),
            ],
            options={
                'verbose_name': 'Dispatch Port',
                'verbose_name_plural': 'Dispatch Ports',
                'ordering': ('-is_default', 'name'),
            },
        ),
        migrations.CreateModel(
            name='OrderAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='In product unit.', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_allocations', to='shared.Customer')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_order_allocations', to=settings.AUTH_USER_MODEL)),
                ('delivery_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_allocations', to='orders.DeliveryOrder')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_order_allocations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Delivery Order Allocation',
                'verbose_name_plural': 'Delivery Order Allocations',
                'ordering': ('delivery_order', '-quantity', 'buyer__name'),
                'default_related_name': 'order_allocations',
                'unique_together': {('delivery_order', 'buyer')},
            },
        ),
        migrations.CreateModel(
            name='InspectionReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('received_quantity', models.DecimalField(decimal_places=2, default=0, help_text='Quantity received on the port in product unit.', max_digits=10)),
                ('shortage', models.DecimalField(decimal_places=2, default=0, help_text='Quantity deficit after transportation in product unit.', max_digits=10, verbose_name='distribution shortage')),
                ('over', models.DecimalField(decimal_places=2, default=0, help_text='Over quantity supplied in product unit.', max_digits=10, verbose_name='over supplied quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inspection_reports', to=settings.AUTH_USER_MODEL)),
                ('order_allocation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='orders.OrderAllocation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_inspection_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inspection Report',
                'verbose_name_plural': 'Inspection Reports',
            },
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='port',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_orders', to='orders.Port'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
