# Generated by Django 2.2.11 on 2020-04-27 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryorder',
            options={'default_related_name': 'delivery_orders', 'ordering': ('-created_at',), 'permissions': [('close_deliveryorder', 'Close delivery order'), ('reopen_deliveryorder', 'Re-open delivery order')], 'verbose_name': 'Delivery Order', 'verbose_name_plural': 'Delivery Orders'},
        ),
    ]
