# Generated by Django 2.2.11 on 2020-03-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryorder',
            name='document_number',
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='lc_number',
            field=models.CharField(default='', max_length=30, unique=True, verbose_name='letter of credit number'),
            preserve_default=False,
        ),
    ]
