# Generated by Django 2.2.11 on 2020-04-28 14:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_union_location'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distribution',
            name='over',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='distribution',
            name='shortage',
        ),
        migrations.CreateModel(
            name='UnionDistribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity received by the labour union in product unit.', max_digits=10, verbose_name='received quantity')),
                ('shortage', models.DecimalField(decimal_places=2, default=0, help_text='Quantity deficit after transportation in product unit.', max_digits=10, verbose_name='dispatch shortage')),
                ('over', models.DecimalField(decimal_places=2, default=0, help_text='Over quantity supplied in product unit.', max_digits=10, verbose_name='over supplied quantity')),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='union_distributions', to='orders.Distribution')),
                ('union', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='union_distributions', to='customers.Union')),
            ],
            options={
                'default_related_name': 'union_distributions',
                'order_with_respect_to': 'distribution',
            },
        ),
    ]
