# Generated by Django 2.2.11 on 2020-04-04 23:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InspectionReport',
            new_name='OrderDistribution',
        ),
        migrations.AlterModelOptions(
            name='orderdistribution',
            options={'verbose_name': 'Delivery Order Distribution', 'verbose_name_plural': 'Delivery Order Distributions'},
        ),
    ]
