# Generated by Django 2.2.11 on 2020-04-28 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_union_location'),
        ('orders', '0002_auto_20200428_1749'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='uniondistribution',
            unique_together={('distribution', 'union')},
        ),
    ]
