# Generated by Django 2.2.11 on 2020-04-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200427_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='office',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
