# Generated by Django 2.2.11 on 2020-04-05 00:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0003_auto_20200405_0256'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderAllocation',
            new_name='Allocation',
        ),
        migrations.RenameModel(
            old_name='OrderDistribution',
            new_name='Distribution',
        ),
    ]
