# Generated by Django 2.2.11 on 2020-04-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200428_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniondistribution',
            name='over',
            field=models.DecimalField(decimal_places=2, help_text='Over quantity supplied in product unit.', max_digits=10, verbose_name='over supplied quantity'),
        ),
        migrations.AlterField(
            model_name='uniondistribution',
            name='shortage',
            field=models.DecimalField(decimal_places=2, help_text='Quantity deficit after transportation in product unit.', max_digits=10, verbose_name='dispatch shortage'),
        ),
    ]
