# Generated by Django 2.2.11 on 2020-04-05 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
        ('orders', '0004_auto_20200405_0302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allocation',
            options={'default_related_name': 'allocations', 'ordering': ('delivery_order', '-quantity', 'buyer__name'), 'verbose_name': 'Delivery Order Allocation', 'verbose_name_plural': 'Delivery Order Allocations'},
        ),
        migrations.AlterModelOptions(
            name='distribution',
            options={'default_related_name': 'distributions', 'ordering': ('delivery_order', '-quantity', 'buyer__name'), 'verbose_name': 'Delivery Order Distribution', 'verbose_name_plural': 'Delivery Order Distributions'},
        ),
        migrations.AlterField(
            model_name='allocation',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations', to='shared.Customer'),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_allocations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='delivery_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='orders.DeliveryOrder'),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='In product unit.', max_digits=10, verbose_name='allocated quantity'),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_allocations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributions', to='shared.Customer'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_distributions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='delivery_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='orders.DeliveryOrder'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_distributions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='distribution',
            unique_together={('delivery_order', 'buyer')},
        ),
    ]
