# Generated by Django 2.2.11 on 2020-05-31 10:09

from django.db import migrations


def move_lc(apps, schema_editor):
    """
    Move a lc_number field to 'Batch' model.
    """
    DeliveryOrder = apps.get_model('orders', 'DeliveryOrder')
    delivery_orders = DeliveryOrder.objects.all()

    for order in delivery_orders:
        if not order.batch.lc_number:
            order.batch.lc_number = order.lc_number
            order.batch.save()


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200526_1708'),
        ('purchases', '0007_batch_lc_number')
    ]

    operations = [
        migrations.RunPython(move_lc)
    ]
