# Generated by Django 2.2.11 on 2020-05-03 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_union_location'),
        ('orders', '0004_auto_20200429_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniondistribution',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='union_distributions', to='customers.Location'),
        ),
        migrations.AlterUniqueTogether(
            name='uniondistribution',
            unique_together=set(),
        ),
    ]
