# Generated by Django 2.2.11 on 2020-03-26 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_deliveryorder_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderallocation',
            options={'default_related_name': 'order_allocations', 'ordering': ('buyer__name',), 'verbose_name': 'Delivery Order Allocation', 'verbose_name_plural': 'Delivery Order Allocations'},
        ),
        migrations.AlterField(
            model_name='orderallocation',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_allocations', to='shared.Customer'),
        ),
        migrations.AlterField(
            model_name='orderallocation',
            name='delivery_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_allocations', to='orders.DeliveryOrder'),
        ),
    ]
