# Generated by Django 2.2.11 on 2020-05-03 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200503_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniondistribution',
            name='location',
            field=models.ForeignKey(default='0eccd61b-33be-4300-8ff1-1bc907efc265', on_delete=django.db.models.deletion.PROTECT, related_name='union_distributions', to='customers.Location'),
            preserve_default=False,
        ),
    ]
