# Generated by Django 2.2.11 on 2020-03-27 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200326_2335'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderallocation',
            options={'default_related_name': 'order_allocations', 'ordering': ('delivery_order', '-quantity', 'buyer__name'), 'verbose_name': 'Delivery Order Allocation', 'verbose_name_plural': 'Delivery Order Allocations'},
        ),
    ]
