# Generated by Django 2.2.11 on 2020-04-07 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200406_1930'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allocation',
            options={'default_related_name': 'allocations', 'ordering': ('delivery_order', 'created_at'), 'verbose_name': 'Delivery Order Allocation', 'verbose_name_plural': 'Delivery Order Allocations'},
        ),
        migrations.AlterModelOptions(
            name='distribution',
            options={'default_related_name': 'distributions', 'ordering': ('delivery_order', 'created_at'), 'verbose_name': 'Delivery Order Distribution', 'verbose_name_plural': 'Delivery Order Distributions'},
        ),
    ]
