# Generated by Django 2.2.11 on 2020-05-03 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_union_location'),
        ('orders', '0006_auto_20200503_1848'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='uniondistribution',
            unique_together={('distribution', 'union', 'location')},
        ),
    ]
