# Generated by Django 2.2.11 on 2020-04-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200407_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='closed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
