# Generated by Django 2.2.11 on 2020-06-07 20:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0010_auto_20200606_1609'),
        ('orders', '0007_remove_deliveryorder_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('lc_number', models.CharField(help_text='Document number for the letter of credit.', max_length=30, verbose_name='L/C number')),
                ('quantity', models.DecimalField(decimal_places=4, help_text='Quantity in the selected product unit.', max_digits=20)),
                ('rate', models.DecimalField(decimal_places=4, help_text='Price is in USD.', max_digits=12)),
                ('year', models.PositiveIntegerField(choices=[(2008, '2008/2009'), (2009, '2009/2010'), (2010, '2010/2011'), (2011, '2011/2012'), (2012, '2012/2013')])),
                ('status', models.CharField(choices=[('OPEN', 'open'), ('CLOSED', 'closed')], default='OPEN', max_length=10)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchases.Product')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchases.Supplier')),
            ],
            options={
                'verbose_name': 'Purchasing Batch',
                'verbose_name_plural': 'Purchasing Batches',
                'ordering': ('-created_at',),
                'permissions': [('close_batch', 'Close purchasing batch'), ('reopen_batch', 'Re-open purchasing batch')],
            },
        ),
    ]
