# Generated by Django 2.2.11 on 2020-05-03 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200503_1918'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='uniondistribution',
            unique_together=set(),
        ),
    ]
