# Generated by Django 2.2.11 on 2020-04-10 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_deliveryorder_closed_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryorder',
            old_name='closed_date',
            new_name='closed_at',
        ),
    ]
