# Generated by Django 2.2.11 on 2020-05-04 19:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_union_location'),
        ('orders', '0008_auto_20200503_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniondistribution',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Quantity received by the union in product unit.', max_digits=10, verbose_name='received quantity'),
        ),
        migrations.CreateModel(
            name='UnionAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity allocated to the union in product unit.', max_digits=10, verbose_name='allocated quantity')),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='union_allocations', to='orders.Allocation')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='union_allocations', to='customers.Location')),
                ('union', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='union_allocations', to='customers.Union')),
            ],
            options={
                'default_related_name': 'union_allocations',
                'order_with_respect_to': 'allocation',
            },
        ),
    ]
