# Generated by Django 2.2.11 on 2020-04-10 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200410_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryorder',
            name='closed_at',
        ),
    ]
