# Generated by Django 2.2.11 on 2020-06-07 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200607_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryorder',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_orders', to='orders.Batch'),
        ),
    ]
