# Generated by Django 2.2.11 on 2020-06-07 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200607_2332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'default_related_name': 'batches', 'ordering': ('-created_at',), 'permissions': [('close_batch', 'Close purchasing batch'), ('reopen_batch', 'Re-open purchasing batch')], 'verbose_name': 'Purchasing Batch', 'verbose_name_plural': 'Purchasing Batches'},
        ),
        migrations.AlterField(
            model_name='batch',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='purchases.Product'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='purchases.Supplier'),
        ),
    ]
