# Generated by Django 2.2.11 on 2020-04-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_remove_deliveryorder_closed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='agreement quantity'),
            preserve_default=False,
        ),
    ]
