# Generated by Django 2.2.11 on 2020-06-09 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20200607_2341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryorder',
            options={'default_related_name': 'delivery_orders', 'ordering': ('created_at',), 'permissions': [('close_deliveryorder', 'Close delivery order'), ('reopen_deliveryorder', 'Re-open delivery order')], 'verbose_name': 'Delivery Order', 'verbose_name_plural': 'Delivery Orders'},
        ),
    ]
