# Generated by Django 2.2.11 on 2020-06-13 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_remove_deliveryorder_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='is_deleted',
        ),
    ]
