# Generated by Django 2.2.11 on 2020-06-14 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_remove_batch_is_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryorder',
            options={'default_related_name': 'delivery_orders', 'ordering': ('created_at',), 'verbose_name': 'Delivery Order', 'verbose_name_plural': 'Delivery Orders'},
        ),
    ]
