# Generated by Django 2.2.13 on 2020-11-03 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20200920_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='uuid',
            field=models.UUIDField(db_index=True, null=True),
        ),
    ]
