# Generated by Django 2.2.13 on 2020-11-03 23:49
import uuid

from django.db import migrations


def generate_unique_port_uuid(apps, schema_editor):
    """
    Generate unique `uuid` values for the `Port` model instances.
    """
    Port = apps.get_model('orders', 'Port')
    for port in Port.objects.all():
        port.uuid = uuid.uuid4()
        port.save()


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_port_uuid'),
    ]

    operations = [
        migrations.RunPython(generate_unique_port_uuid)
    ]
