# Generated by Django 2.2.13 on 2020-11-03 23:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20201104_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
